---
title: 'Homework3: Logistic Regression'

output:
  pdf_document: default
  html_notebook: default
subtitle: |-
  CSE6242 - Data and Visual Analytics - Spring 2018

---
_GTUser:vchugh3_

---
```{r setup, include=FALSE}
setwd("C:/Users/vchugh/Documents/Academics/Georgia Tech/Spring 2018/CS 6242 Data and Visual Analytics/Assignments/HW3/mnist/mnist")
knitr::opts_chunk$set(echo = TRUE)
```

1. Data Preprocessing [50 points]
```{r Data Preprocessing}
setwd("C:/Users/vchugh/Documents/Academics/Georgia Tech/Spring 2018/CS 6242 Data and Visual Analytics/Assignments/HW3/mnist/mnist")
training_set <- read.csv ('mnist_train.csv', header = FALSE)
test_set <- read.csv ('mnist_test.csv', header = FALSE)

# Partitioning the training dataset
train_0_1 <- training_set[,((training_set[785,] == 0) | (training_set[785,] == 1))]
train_3_5 <- training_set[,((training_set[785,] == 3) | (training_set[785,] == 5))]

# Partitioning the testing dataset
test_0_1 <- test_set[,((test_set[785,] == 0) | (test_set[785,] == 1))]
test_3_5 <- test_set[,((test_set[785,] == 3) | (test_set[785,] == 5))]

sprintf("Dimensions of train_0_1 are %i x %i", dim(train_0_1)[1], dim(train_0_1)[2])
sprintf("Dimensions of train_3_5 are %i x %i", dim(train_3_5)[1], dim(train_3_5)[2])
sprintf("Dimensions of test_0_1 are %i x %i", dim(test_0_1)[1], dim(test_0_1)[2])
sprintf("Dimensions of test_3_5 are %i x %i", dim(test_3_5)[1], dim(test_3_5)[2])

# Remove the last Row from each of the data frames created.
train_data_0_1 <- train_0_1[1:784,]
train_data_3_5 <- train_3_5[1:784,]
test_data_0_1 <- test_0_1[1:784,]
test_data_3_5 <- test_3_5[1:784,]

train_labels_0_1 <- train_0_1[785,]
train_labels_3_5 <- train_3_5[785,]
test_labels_0_1 <- test_0_1[785,]
test_labels_3_5 <- test_3_5[785,]

#Visualize 1 image from each class to ensure you have read in the data correctly. So you should show 4 images, with labels 0, 1, 3 and 5.

rotate <- function(x) t(apply(x, 2, rev))

#Please feel free to uncomment JPEG generation and dev.off statements if you need to save the image on file. I just created the pdf out of the .rmd file.
#Visualize 0
image0_mat <- rotate(matrix(unlist(train_data_0_1[1:784,1]), nrow = 28, byrow = FALSE))
#jpeg("image_0.jpg")
image(z = image0_mat, col = gray(0:255/255))
title('Image from Class for 0')
#dev.off()

#Visualize 1
image1_mat <- rotate(matrix(unlist(train_data_0_1[1:784,12665]), nrow = 28, byrow = FALSE))
#jpeg("image_1.jpg") + 
image(z = image1_mat, col = gray(0:255/255))
title('Image from Class for 1')
#dev.off()

#Visualize 3
image3_mat <- rotate(matrix(unlist(train_data_3_5[1:784,1]), nrow = 28, byrow = FALSE))
#jpeg("image_3.jpg")
image(z = image3_mat, col = gray(0:255/255))
title('Image from Class for 3')
#dev.off()

#Visualize 5
image5_mat <- rotate(matrix(unlist(train_data_3_5[1:784,11520]), ncol = 28, byrow = FALSE))
#jpeg("image_5.jpg")
image(z = image5_mat, col = gray(0:255/255))
title('Image from Class for 5')
#dev.off()
```
